### ISSUE TITLE
Expand icon prop

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#2] opened 2019-08-03 17:15 UTC
Currently the `icon`, `iconList` and `iconSet` props in many components accept just a `String` that is automatically mapped to the `fas` subset of FontAwesome icons. 

Any deviation from this icon set must be achieved by populating the respective add-on slot housing the icon. This can get cumbersome and unnecessarily verbose.

A viable alternative would be to allow passing each icon either as a `String` (that is programmatically mapped to `['fas', icon]`) or as an array listing the subset and the icon name. 

This approach would also simplify template declarations of `FontAwesomeIcon` components 
as this functionality is implemented in the `FontAwesomeIcon` Vue component itself).

```html
<FontAwesomeIcon :icon="icon"/>
```

**Comment by sabina-rohman** [comment] 2019-10-01 19:46
Hi I am a Outreachy Fall 2019 applicant. I would like to work on this issue. Can you please assign it to me?

**Comment by dhruvkb** [comment] 2019-10-02 13:13
Sure. Take it up!

**Comment by dhruvkb** [comment] 2019-10-12 04:33
@sabina-rohman any updates?

**Comment by sabina-rohman** [comment] 2019-10-13 12:49
@dhruvkb oh so sorry, didn't realize it was already assigned to me! I accepted and am working on a separate mozilla task at the moment. I could try this one once I complete the current task. Though I am not sure when. For now please feel free to un-assign it in case anyone else may want to pick it up. Thanks :)

**Comment by dhruvkb** [comment] 2019-10-13 14:58
I'm unassigning this for time being. Feel free to take it up again if you are freed from the other task and this hasn't been taken up in the meantime.

**Comment by sayima-n** [comment] 2019-10-21 09:19
Hello @dhruvkb I'm an Outreachy applicant and would like to take this up if its available. I would start with all the `icon` props components, submit pull request and then the `iconList` and finally `iconSet`. What do you think?

**Comment by dhruvkb** [comment] 2019-10-21 09:29
@sayima-n sounds good!

**Comment by sayima-n** [comment] 2019-10-21 09:36
Thank you! Talk to you soon

**Comment by sayima-n** [comment] 2019-10-24 16:55
@dhruvkb in addition to not allowing any non Creative Commons icon within it's `icon-list` prop, the `LicenseIconography` is the only component not to provide a slot to render alternative icons. So it seems that this component refuses non Creative Commons icons by design. For this reason I'm wondering if the `icon-list` prop should nevertheless be made to accept any icons or left as is?

**Comment by dhruvkb** [comment] 2019-10-24 20:46
@sayima-n the `LicenseIconography` component is meant solely to depict icons that are parts of CC licenses. That is why their so constrained in terms of what icons they can show. 

Since the component has a very narrow usecase and its icons are only available in the ‘fab’ set, you can leave the prop there as is.

**Closed** 2019-11-29 22:48 UTC
Labels: aspect: code, duration: standard, good first issue, improvement: enhancement, priority: moderate
